### ISSUE TITLE
v1.4.6 color changes introduces unintended button styling

### ISSUE THREAD

**Issue by djflan** [catppuccin/visual-studio#25]
@eberthold  Had to undo the changes that were part of your pr (release 1.4.6 has them, 1.4.7 does not).
It seems that button changes were made - I'm not sure how I didn't spot it earlier.

This will need to be fixed before we can incorporate the changes you made.

Here are some screenshots from that change:
![buttons](https://github.com/catppuccin/visual-studio/assets/7758156/acd07ee6-5126-4860-a52c-4a599e581757)
![other](https://github.com/catppuccin/visual-studio/assets/7758156/e25f5682-9068-4988-9e37-0f7eb91e919f)

The tabs are unreadable - also a blue line now appears on top of the output window and some additional windows.

**Comment by eberthold** [comment]
Sorry for the inconvenience caused by the script of mine.

The unreadable tabs were caused by the fact that the themes use transparency instead of FF opacity which was the assumption of mine based on all the colors I was aware of in the styleguide - the script now respects those transparency values

The blue bar seems to be caused by the CT_RAW and CT_INVALID values in the <Foreground> and <Background> tags. Because I have no clue what they even mean, the script now simply uses the value from the source script.

Those two issues are gone with #26
