### ISSUE TITLE
Lots of differences between vs code and visual studio

### ISSUE THREAD

**Issue by mddheeraj** [catppuccin/visual-studio#3]
I see lots of difference between vs code and visual studio. I applied same theme mocha. In visual studio I don't see the spaces and the color schema is more different than vs code.  Can we have the same schema like vs code for visual studio.
![vscodevsvisualstudio](https://user-images.githubusercontent.com/20344363/231896926-6f2eb6f3-972b-4ce2-94c4-451fc05a0e23.png)
vs code color schema looks better.

**Comment by nekowinston** [comment]
Hey there!

VSCode is currently far from perfect too, and is inconsistent between languages (Rust looks diffeerent to TypeScript and Python).

I have a PR open to address this issue, but haven't got around to giving it any attention since I'm not daily driving VSCode as my editor. https://github.com/catppuccin/vscode/pull/53

Ideally, all our Editors should follow the [JetBrains](https://github.com/catppuccin/jetbrains) syntax highlighting, since we put most of our effort into that one, when we re-evaluated our 0.2.0 highlights late last summer.

I would appreciate if people could help out with making the Editors more alike than they are now.

**Comment by mddheeraj** [comment]
if we can see the spaces at least in visual studio that would really help me and my team members.

**Comment by nekowinston** [comment]
Oh yeah, I understand that. I just meant to clarify that the "source of truth" for the highlights we're aiming for is documented in the [upcoming Styleguide](https://github.com/catppuccin/catppuccin/blob/ca8bf8980cfa96e75985c86fb7f06c76c150fe0e/docs/style-guide.md#code-editors), and implemented in JetBrains at the moment. Newer ports like JetBrains Fleet and KSyntaxHighlighting already used those as Guidelines.

Specific to this port: If someone wants to add the whitespace highlights to improve readability, I would prefer this issue to remain open to track the implementation of the full style guide.

**Comment by djflan** [comment]
@mddheeraj 
I believe I have fixed the spaces issue in v1.1.0 - please try this version. For what it is worth, I am aiming to adhere more to the style guidelines as @nekowinston kindly pointed out. 

In addition to this, I have removed the pkgdef files and added the vstheme files (pkgdefs are generated at build). This will make it much easier to modify the themes as you can use tooling to do so.

Finally, it is worth pointing out that the theming engines for VS and VSCode are very, very different. The best we can hope for it to 'get close' to matching look and feel. There are some things we can't do in VS (for instance, multiple colors for braces) and vice-versa. That said, you are more than welcome to branch and make your own additions to match theming. 

Oh! ...added Arm64 support as well :)

Cheers!

**Comment by mddheeraj** [comment]
the version new version have spaces. Nice!!!
![mouseoverselectioncan'tsee](https://user-images.githubusercontent.com/20344363/232540174-fda80194-d40b-4056-bb54-014886ba84fc.png)
